discovery:
  exclusions:
  - front/
  - front\
  - build/
 # - pycrunch/tests
  - test_discovery_specs_demo.py
engine:
  runtime: pytest
env:
  DJANGO_SETTINGS_MODULE: insuredportal.settings.local
pinned-tests:
- pycrunch.tests.tests_configuration:test_environment_vars
- tests_two:test_dummy
- tests_one:test_regexp
- tests_two:test_z
