discovery:
  exclusions:
  - front/
  - front\
  - build/
  - test_discovery_specs_demo.py
engine:
  cpu-cores: 4
  multiprocessing-threshold: 4
  runtime: pytest
  timeout: 5
  load-pytest-plugins: false
env:
  DJANGO_SETTINGS_MODULE: insuredportal.settings.local
pinned-tests:
- pycrunch.tests.tests_configuration:test_environment_vars
- tests_two:test_pin_sleep120
